version: '3'

services:
  # Laravel application (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - backend

  # Nginx
  web:
    image: nginx:alpine
    ports:
      - "80:80"  # Mapeia a porta 80 do host para a porta 80 do container
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  # MongoDB
  mongodb:
    image: mongo
    container_name: oliveira_trust
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
